version: "3"
services:
  thingydb:
    image: mongo:3.2.4
    container_name: "mongo"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: com.todo/thingy
    ports:
      - 8080:8080
    links:
      - thingydb
